### ISSUE TITLE
ImmovableCulturalProperty subclass di cis:Site?

### ISSUE THREAD

**Issue by MiBACT-LinkedOpenData** [MiBACT-LinkedOpenData/ArCo#10]
Non sono sicura di questo allineamento semantico. Un site, per Cultural-ON rappresenta un luogo fisico georeferenziato relativo all'Istituto e luogo della Cultura e per ICCD tale concetto è esplicitamente ricondotto al contenitore fisico. Una subclass eredita tutte le proprietà della superclasse? Perchè nel caso dei beni culturali immobili non è detto che un edificio architettonico sia anche la sede di un luogo della cultura, tutt'altro o che sia un "contenitore di beni culturali"

**Comment by ValentinaCarriero** [comment]
Sarebbe quindi concettualmente più corretto per voi, piuttosto che definire ImmovableCulturalProperty come subclass di cis:Site, definirla come classe non disgiunta da cis:Site (per quei casi in cui invece è sia bene culturale sia contenitore fisico)?
E associare poi a ImmovableCulturalProperty, in maniera diretta, e non tramite la proprietà :isInSite (come accade per i beni mobili), le informazioni sulla localizzazione geografico-amministrativa?

**Comment by MiBACT-LinkedOpenData** [comment]
Si, la tua interpretazione è corretta!
Grazie mille!
Chiara

Inviato da iPhone

Il giorno 23 mar 2018, alle ore 17:51, ValentinaCarriero <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Sarebbe quindi concettualmente più corretto per voi, piuttosto che definire ImmovableCulturalProperty come subclass di cis:Site, definirla come classe non disgiunta da cis:Site (per quei casi in cui invece è sia bene culturale sia contenitore fisico)?
E associare poi a ImmovableCulturalProperty, in maniera diretta, e non tramite la proprietà :isInSite (come accade per i beni mobili), le informazioni sulla localizzazione geografico-amministrativa?
