### ISSUE TITLE
Esempi di Query Sparql - prefisso non utile?

### ISSUE THREAD

**Issue by shin81** [MiBACT-LinkedOpenData/ArCo#12]
Tra gli esempi di query SPARQL presenti sul sito, quello sulla seconda riga, terza colonna ("Quali sono i beni culturali immateriali descritti nelle schede attualmente pubblicate?") funziona anche senza il secondo prefisso (PREFIX cis: <http://dati.beniculturali.it/cis/>)

**Comment by simonegasperoni** [comment]
i prefissi principali è come se fossero già scritti nella form dell endpoint, puoi consultarli tramite il link Namespace Prefixes.. ma forse il link non funziona..
