### ISSUE TITLE
shortcut per agganciare l'indirizzo direttamente alle arco:MovableCulturalProperty

### ISSUE THREAD

**Issue by giorgiobevilacqua** [MiBACT-LinkedOpenData/ArCo#14]
In pochi casi (750)  le arco:MovableCulturalProperty sono agganciate direttamente all'indirizzo del csi:Site in questo modo:
```
PREFIX arco: <http://www.w3id.org/arco/core/>
PREFIX cis: <http://dati.beniculturali.it/cis/>
PREFIX locgeoamm: <http://www.w3id.org/arco/locgeoamm/>
SELECT count distinct ?entity as ?count
WHERE{
?entity a arco:MovableCulturalProperty .
?entity cis:siteAddress ?address .
}
```

Quando invece ci si aspetterebbe che fosse così:
```
PREFIX arco: <http://www.w3id.org/arco/core/>
PREFIX cis: <http://dati.beniculturali.it/cis/>
PREFIX locgeoamm: <http://www.w3id.org/arco/locgeoamm/>
SELECT count distinct ?entity
WHERE{
?entity a arco:MovableCulturalProperty .
?entity locgeoamm:isInSite ?site .
?site cis:siteAddress ?siteAddress .
}
```

Si potrebbe trasformare l'errore di mappatura della prima query in una feature! 
Se l'indirizzo in cui si trova bene viene annotato non solo sul cis:Site ma anche direttamente su arco:MovableCulturalProperty (con un'altra property) si alleggeriscono le query per gli sviluppatori.

**Comment by Valentina10** [comment]
Abbiamo corretto l'errore di mappatura, e abbiamo creato la proprietà che collega direttamente il bene culturale all'indirizzo della sua collocazione fisica attuale (locgeoamm:culturalPropertyAddress). Per via di un errore nella trasformazione dei dati della seconda release, non sono però ancora attualmente disponibili questi dati, che saranno certamente integrati nella terza release. Considero quindi la issue come risolta.
