### ISSUE TITLE
Namespaces dei dataset e riferimenti alle ontologie

### ISSUE THREAD

**Issue by MiBACT-LinkedOpenData** [MiBACT-LinkedOpenData/ArCo#23]
Scaricando un dataset da Virtuoso tra i namespace richiamati si vedono i seguenti (che non corrispondono a quelli dichiarati nelle ontologie):

xmlns:j.0="http://www.w3id.org/arco/core/" 
xmlns:j.1="https://w3id.org/arco/core/" 
xmlns:j.2="https://w3id.org/arco/location/" 
xmlns:j.3="http://dati.beniculturali.it/cis/" 
xmlns:j.4="https://w3id.org/arco/identifier/" 
xmlns:j.5="https://w3id.org/arco/culturaldefinition/" 
xmlns:j.6="https://w3id.org/arco/cpdescription/" 
xmlns:j.7="https://w3id.org/arco/cataloguerecord/"

**Comment by Valentina10** [comment]
Le errate corrispondenze tra i namespaces usati per produrre i dati e quelli dichiarati nelle ontologie sono state risolte e la correzione sarà visibile nella prossima release!
