### ISSUE TITLE
Uso degli acronimi e delle sigle

### ISSUE THREAD

**Issue by MiBACT-LinkedOpenData** [MiBACT-LinkedOpenData/ArCo#6]
I valori di CataloguingLevel si possono sciogliere scrivendo la sigla  in maniera estesa?

**Comment by Valentina10** [comment]
Certo, potete darci le traduzioni in inglese dei tre livelli?

**Comment by MiBACT-LinkedOpenData** [comment]
Anzichè proporre la traduzione letterale del livello di ricerca (inventory, pre-catalogue e catalogue) che rischia di essere poco significativa, pensiamo di tradurre in inglese con I=minimum, P=medium e C=detailed
